# Generated by Django 4.1.2 on 2022-10-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_alter_myuser_birthday'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
