# Generated by Django 4.1.2 on 2022-10-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='username'),
        ),
    ]
